name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Deploy to EC2 by SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/microservices

            echo "Pulling latest code..."
            git pull

            echo "Stopping containers..."
            sudo docker compose down

            echo "Building new images..."
            sudo docker compose up -d --build


            echo "Deployment completed successfully!"